title: Evan Bohler's Homepage
page-top-title: Evan Bohler
top-section-bg-text: Computer Science Student
home-subtitle: Evan Bohler
copyright-text: '&copy; Evan Bohler 2023-2024. All Rights Reserved.'
